name: Reusable user config build

on:
  workflow_call:
    inputs:
      build_matrix:
        description: "Path to the build matrix file"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.build_matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add the rest of your steps as needed (build, preparation, etc.)
